title: RadioPi Club
email: askom@radiopi.club
logo: /assets/img/radiopi-logo.png
description: Hamradio Raspberry Pi OS for dummies.
show_downloads: true
google_analytics: UA-170516589-1
theme: jekyll-theme-minimal

date_format: "%F"

timezone: Asia/Shanghai

plugins:
 - jekyll-seo-tag